### ISSUE TITLE
Dim error When using a local pretrained model to train a global model

### ISSUE THREAD

**Issue by YCCCCM** [li-ronghui/LODGE#25]
Traceback (most recent call last):
  File "train.py", line 192, in <module>
    main()
  File "train.py", line 171, in main
    model.load_state_dict(new_state_dict, strict=False)
  File "/home/ycbx/projects/LODGE/dld/models/modeltype/base.py", line 208, in load_state_dict
    super().load_state_dict(state_dict, strict)
  File "/home/ycbx/anaconda3/envs/lodge/lib/python3.8/site-packages/torch/nn/modules/module.py", line 2189, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for Global_Module:
	size mismatch for DanceDecoder.null_cond_embed: copying a param with shape torch.Size([1, 256, 512]) from checkpoint, the shape in current model is torch.Size([1, 1024, 512]).
	size mismatch for diffusion.model.null_cond_embed: copying a param with shape torch.Size([1, 256, 512]) from checkpoint, the shape in current model is torch.Size([1, 1024, 512]).
	size mismatch for diffusion.master_model.null_cond_embed: copying a param with shape torch.Size([1, 256, 512]) from checkpoint, the shape in current model is torch.Size([1, 1024, 512]).

When I modified finedance_fea139.yaml, the FINEDANCE.full_seq_len line didn't work, and after training it was still [1,256,512]
latent_dim:  [1, 256]  #[512, 135]    # [${FINEDANCE.full_seq_len}, ${DATASET.NFEATS}]      #  # latent dimension

And when I used the pre-trained model downloaded from Google Cloud Drive, I also reported that dimension error. (exp/.../checkpoints/epoch=299.ckpt)

When I manually modified all the parameters for FINEDANCE.full_seq_len, the following error occurred
Traceback (most recent call last):
  File "train.py", line 192, in <module>
    main()
  File "train.py", line 179, in main
    trainer.fit(model, datamodule=datasets[0])
  File "/home/ycbx/anaconda3/envs/lodge/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 608, in fit
    call._call_and_handle_interrupt(
  File "/home/ycbx/anaconda3/envs/lodge/lib/python3.8/site-packages/pytorch_lightning/trainer/call.py", line 38, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ycbx/anaconda3/envs/lodge/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 650, in _fit_impl
    self._run(model, ckpt_path=self.ckpt_path)
  File "/home/ycbx/anaconda3/envs/lodge/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1112, in _run
    results = self._run_stage()
  File "/home/ycbx/anaconda3/envs/lodge/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1191, in _run_stage
    self._run_train()
  File "/home/ycbx/anaconda3/envs/lodge/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1204, in _run_train
    self._run_sanity_check()
  File "/home/ycbx/anaconda3/envs/lodge/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1276, in _run_sanity_check
    val_loop.run()
  File "/home/ycbx/anaconda3/envs/lodge/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/ycbx/anaconda3/envs/lodge/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/ycbx/anaconda3/envs/lodge/lib/python3.8/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/ycbx/anaconda3/envs/lodge/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 137, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/ycbx/anaconda3/envs/lodge/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 234, in _evaluation_step
    output = self.trainer._call_strategy_hook(hook_name, *kwargs.values())
  File "/home/ycbx/anaconda3/envs/lodge/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1494, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/ycbx/anaconda3/envs/lodge/lib/python3.8/site-packages/pytorch_lightning/strategies/strategy.py", line 390, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/home/ycbx/projects/LODGE/dld/models/modeltype/Local_Module.py", line 425, in validation_step
    return self.allsplit_step("val", batch, batch_idx, epoch)
  File "/home/ycbx/projects/LODGE/dld/models/modeltype/Local_Module.py", line 352, in allsplit_step
    samples = self.diffusion.ddim_sample(
  File "/home/ycbx/anaconda3/envs/lodge/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/ycbx/projects/LODGE/dld/models/architectures/diffusion.py", line 277, in ddim_sample
    pred_noise, x_start, *_ = self.model_predictions(x, cond, genre, time_cond, clip_x_start = self.clip_denoised)
  File "/home/ycbx/projects/LODGE/dld/models/architectures/diffusion.py", line 170, in model_predictions
    model_output = self.model.guided_forward(x, cond, genre, t, weight)
  File "/home/ycbx/projects/LODGE/dld/models/architectures/model.py", line 870, in guided_forward
    unc = self.forward(x, cond_embed, genre, times, cond_drop_prob=1)
  File "/home/ycbx/projects/LODGE/dld/models/architectures/model.py", line 928, in forward
    cond_tokens = torch.where(keep_mask_embed, cond_tokens, null_cond_embed)
RuntimeError: The size of tensor a (256) must match the size of tensor b (1024) at non-singleton dimension 1

**Comment by xiaxinyu20020718** [comment]
I'm having the same problem, is there a solution?

**Comment by YCCCCM** [comment]
> I'm having the same problem, is there a solution?

I solved it. 

Modify the configuration file: finedance_fea139_finetune_v2.yaml 

model:
  target: 'modules'
  vae_type: 'no'
  
  vae: true # whether vae model
  model_type: Local_Module # model type
  condition: 'music'
  latent_dim: [1024, 256]  #[512, 135]    # [${FINEDANCE.full_seq_len}, ${DATASET.NFEATS}]      #  # latent dimension

 latent_dim: [1024, 256]  not [1, 256].

**Comment by xinyuzhang915** [comment]
FINEDANCE:
  mix: False           # weather do mix data augmentation
  # full_seq_len: 1024
  full_seq_len: 256   
I tried this change, and it worked.
