### ISSUE TITLE
SMPLH_male.pkl  problem

### ISSUE THREAD

**Issue by sandrodevdariani** [li-ronghui/LODGE#6]
I downloaded model from https://mano.is.tue.mpg.de/download.php and using SMPLH_male.pkl but getting this error. any fix?

```
(pytorch3d) (env) ssss@sandris-MacBook-Pro LODGE1 % python3.10 render.py --modir '/Users/ssss/Desktop/dance/LODGE1/data/finedance/motion' 
cpu
055.npy
WARNING: You are using a SMPL+H model, with only 10 shape coefficients.
Traceback (most recent call last):
  File "/Users/ssss/Desktop/dance/LODGE1/render.py", line 405, in <module>
    visualizer = MovieMaker(save_path=save_path)
  File "/Users/ssss/Desktop/dance/LODGE1/render.py", line 73, in __init__
    self.smplh = SMPLH(SMPLH_path, use_pca=False, flat_hand_mean=True)
  File "/Users/ssss/anaconda3/envs/pytorch3d/lib/python3.10/site-packages/smplx/body_models.py", line 601, in __init__
    left_hand_components = data_struct.hands_componentsl[:num_pca_comps]
AttributeError: 'Struct' object has no attribute 'hands_componentsl'
```

**Comment by li-ronghui** [comment]
In the render file, we set three optional model (SMPL, SMPLH, SMPLX) to render the dance results.  Actually, smplx is more suitable for rendering our data.
Therefore, you can only retain SMPLX and have a try : )
Or, you may get help from   https://github.com/vchoutas/smplify-x/issues/178
